terraform {
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
    }
    helm = {
      source = "hashicorp/helm"
    }
  }
}

# Chaos Mesh is deployed by Terraform, not as an ArgoCD Application like
# every workload here. Architecturally it is platform tooling in the same
# category as ArgoCD itself: it operates on the cluster rather than running
# in it, and letting the GitOps controller manage a tool built to disrupt
# GitOps-managed resources is a circularity worth avoiding.
#
# The stronger reason is chaos-mesh issue 4764, an open bug on exactly this
# stack (ArgoCD, EKS, containerd). With webhook.certManager.enabled = false,
# which is the chart default and what we use, the admission webhook's CA,
# cert and key are generated by Helm at render time via genCA and
# genSignedCert. They are not generated by the controller at runtime. That
# generation is non-deterministic, so a controller re-rendering the chart on
# every sync produces a fresh random cert each time, sees permanent drift,
# and selfHeal writes a caBundle that no longer matches the key the webhook
# server is serving. Creating any chaos CR then fails with "x509:
# certificate signed by unknown authority". Terraform renders once and keeps
# the result in state, so nothing re-renders to disagree with it.
#
# Corollary, and a real constraint: any future helm upgrade of this release
# regenerates the certs. A chart version bump is a webhook-affecting change,
# so verify it by creating a chaos CR afterwards, not just by pods going
# Ready.

resource "kubernetes_namespace_v1" "chaos_mesh" {
  metadata {
    name = "chaos-mesh"

    # The cluster_name input exists mainly to give this module an explicit
    # dependency edge on module.eks, so a targeted destroy of module.eks
    # sweeps Chaos Mesh up with it (the same reason module.argocd is covered
    # without being named). The chart itself needs no cluster name, so the
    # value is spent on a label.
    labels = {
      "railhead.io/cluster" = var.cluster_name
    }
  }
}

resource "helm_release" "chaos_mesh" {
  name       = "chaos-mesh"
  repository = "https://charts.chaos-mesh.org"
  chart      = "chaos-mesh"
  version    = var.chaos_mesh_chart_version
  namespace  = kubernetes_namespace_v1.chaos_mesh.metadata[0].name

  # runtime and socketPath are the load-bearing pair. The chart defaults to
  # docker and /var/run/docker.sock, wrong for EKS 1.34 (containerd 2.2.5).
  # Getting them wrong is not a crash: chaos-daemon starts, reports Ready,
  # and silently injects nothing, the same failure shape as the Alloy
  # empty-ClusterRole bug. These values match the chart's own commented
  # containerd example exactly.
  #
  # replicaCount drops from the chart default of 3. On a two-node cluster a
  # third controller replica cannot land on a distinct node, so it buys no
  # availability.
  #
  # securityMode = false is deliberate, not an oversight. It disables the
  # dashboard's credential prompt and lets it use its service account.
  # Acceptable only because the dashboard is ClusterIP with no ingress and is
  # reached by kubectl port-forward alone. If it is ever given an ingress,
  # this must flip back to true first.
  #
  # persistentVolume and ingress are already false by default. They are
  # stated anyway so a reader sees they were decided, not inherited.
  values = [<<-YAML
    chaosDaemon:
      runtime: containerd
      socketPath: /run/containerd/containerd.sock

    controllerManager:
      replicaCount: 1

    dashboard:
      securityMode: false
      persistentVolume:
        enabled: false
      ingress:
        enabled: false
  YAML
  ]
}
